live_config_reload = true

import = [
  "~/.config/alacritty/themes/themes/dracula.toml"
]

[shell]
program = "/bin/fish"

[window]
opacity = 0.9
decorations = "Full"
padding = { x = 8, y = 4 }
dynamic_padding = true
dynamic_title = false
title = "insmnxa"

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 11.0

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Underline", blinking = "On" }
