live_config_reload = true

import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[shell]
program = "/bin/fish"

[window]
opacity = 0.85
decorations = "Full"
padding = { x = 8, y = 4 }
dynamic_title = false
title = "insmnxa"

[font]
family = { family = "FiraCode", style = "Regular" }
size = 11.0

[mouse]
hide_when_typing = true
